liquibase-dialect/pom.xml, liquibase-dialect/src/main/java/tech/ydb/liquebase/database/YdbDatabase.java, liquibase-dialect/src/main/java/tech/ydb/liquebase/sqlgenerator/CreateIndexGeneratorYdb.java, liquibase-dialect/src/main/resources/META-INF/services/liquibase.database.Database, liquibase-dialect/src/main/resources/META-INF/services/liquibase.sqlgenerator.SqlGenerator
Please check the type of change your PR introduces:
=> Create liquibase YdbDatabase.java and CreateIndexGeneratorYdb.java

liquibase-dialect/src/main/java/tech/ydb/liquibase/database/YdbDatabase.java, liquibase-dialect/src/main/java/tech/ydb/liquibase/sqlgenerator/CreateIndexGeneratorYdb.java, liquibase-dialect/src/main/java/tech/ydb/liquibase/sqlgenerator/CreateTableGeneratorYdb.java, liquibase-dialect/src/main/resources/META-INF/services/liquibase.database.Database, liquibase-dialect/src/main/resources/META-INF/services/liquibase.sqlgenerator.SqlGenerator
Please check the type of change your PR introduces:
=> [Liquibase]: Create Table sql generator + rename package

jooq-dialect/pom.xml
=> Updated jooq pom.xml

.github/workflows/publish-jooq-dialect.yaml
=> Workaround for OSSRH-66257

jooq-dialect/pom.xml
=> Add sources and javadoc to publish

.github/workflows/ci-liquibase-dialect.yaml, .github/workflows/publish-liquibase-dialect.yaml, liquibase-dialect/pom.xml
=> [Liquibase]: CI and publish Maven repository

liquibase-dialect/src/main/java/tech/ydb/liquibase/database/YdbDatabase.java, liquibase-dialect/src/test/java/tech/ydb/liquibase/YdbDatabaseLiquibaseChangeLogStateTest.java
=> [Liquibase]: Fix datetime insert SQLStatement

liquibase-dialect/src/main/java/tech/ydb/liquibase/database/YdbDatabase.java, liquibase-dialect/src/test/java/tech/ydb/liquibase/YdbDatabaseLiquibaseChangeLogStateTest.java, liquibase-dialect/src/test/resources/changelogs/migration/seasons_and_episodes.xml
=> Fix datetime

.github/workflows/ci-liquibase-dialect.yaml
=> [Liquibase]: SpringBoot App Example in CI

.github/workflows/ci-liquibase-dialect.yaml, README.md, hibernate-dialect-v5/README.md, hibernate-dialect/README.md, liquibase-dialect/README.md, liquibase-dialect/pom.xml
=> Update README.md files

liquibase-dialect/pom.xml
=> [Liquibase]: Shaded dependencies from liquibase-parent-pom org.slf4j

liquibase-dialect/pom.xml
=> [Liquibase]: Delete parent POM

liquibase-dialect/CHANGELOG.md, liquibase-dialect/pom.xml
Please check the type of change your PR introduces:
Issue Number: N/A
-
-
-
=> [Liquibase]: Added CHANGELOG.md, switch version to 1.0.0-SNAPSHOT

hibernate-dialect-v5/src/main/java/tech/ydb/hibernate/dialect/YdbDialect.java, hibernate-dialect-v5/src/main/java/tech/ydb/hibernate/dialect/types/LocalDateTimeType.java, hibernate-dialect-v5/src/main/java/tech/ydb/hibernate/dialect/types/LocalDateTimeTypeDescriptor.java, hibernate-dialect-v5/src/test/java/tech/ydb/hibernate/types/Employee.java, hibernate-dialect-v5/src/test/java/tech/ydb/hibernate/types/TypesTest.java, hibernate-dialect/pom.xml, hibernate-dialect/src/main/java/tech/ydb/hibernate/dialect/YdbDialect.java, hibernate-dialect/src/main/java/tech/ydb/hibernate/dialect/types/LocalDateTimeJavaType.java, hibernate-dialect/src/main/java/tech/ydb/hibernate/dialect/types/LocalDateTimeJdbcType.java, hibernate-dialect/src/test/java/tech/ydb/hibernate/student/StudentsRepositoryTest.java, hibernate-dialect/src/test/java/tech/ydb/hibernate/types/Employee.java, hibernate-dialect/src/test/java/tech/ydb/hibernate/types/TypesTest.java, hibernate-dialect/src/test/java/tech/ydb/hibernate/user/UserRepositoryTest.java
=> [Hibernate 5 / 6]: Hibernate 5 / 6 supports LocalDateTime

liquibase-dialect/src/main/java/tech/ydb/liquibase/change/LoadDataChangeYdb.java, liquibase-dialect/src/main/java/tech/ydb/liquibase/change/LoadUpdateDataChangeYdb.java, liquibase-dialect/src/main/java/tech/ydb/liquibase/database/YdbDatabase.java, liquibase-dialect/src/main/java/tech/ydb/liquibase/sqlgenerator/InsertOrUpdateGeneratorYdb.java, liquibase-dialect/src/main/java/tech/ydb/liquibase/type/BytesTypeYdb.java, liquibase-dialect/src/main/java/tech/ydb/liquibase/type/DateTypeYdb.java, liquibase-dialect/src/main/java/tech/ydb/liquibase/type/DecimalTypeYdb.java, liquibase-dialect/src/main/java/tech/ydb/liquibase/type/FloatTypeYdb.java, liquibase-dialect/src/main/java/tech/ydb/liquibase/type/OtherTypeYdb.java, liquibase-dialect/src/main/java/tech/ydb/liquibase/type/TimeTypeYdb.java, liquibase-dialect/src/main/java/tech/ydb/liquibase/type/TimestampTypeYdb.java, liquibase-dialect/src/main/resources/META-INF/services/liquibase.change.Change, liquibase-dialect/src/main/resources/META-INF/services/liquibase.sqlgenerator.SqlGenerator, liquibase-dialect/src/test/java/tech/ydb/liquibase/YdbDatabaseCSVLoadTest.java, liquibase-dialect/src/test/resources/changelogs/changelog-load-csv.xml, liquibase-dialect/src/test/resources/changelogs/csv/test-insert.csv, liquibase-dialect/src/test/resources/changelogs/csv/test-upsert.csv, liquibase-dialect/src/test/resources/changelogs/csv/test.csv
=> [Liquibase]: Load CSV fila data UPSERT / INSERT

liquibase-dialect/src/main/java/tech/ydb/liquibase/type/BoolTypeYdb.java, liquibase-dialect/src/main/java/tech/ydb/liquibase/type/BytesTypeYdb.java, liquibase-dialect/src/main/java/tech/ydb/liquibase/type/DateTypeYdb.java, liquibase-dialect/src/main/java/tech/ydb/liquibase/type/DecimalTypeYdb.java, liquibase-dialect/src/main/java/tech/ydb/liquibase/type/DoubleTypeYdb.java, liquibase-dialect/src/main/java/tech/ydb/liquibase/type/FloatTypeYdb.java, liquibase-dialect/src/main/java/tech/ydb/liquibase/type/IntTypeYdb.java, liquibase-dialect/src/main/java/tech/ydb/liquibase/type/LongTypeYdb.java, liquibase-dialect/src/main/java/tech/ydb/liquibase/type/OtherTypeYdb.java, liquibase-dialect/src/main/java/tech/ydb/liquibase/type/TextTypeYdb.java, liquibase-dialect/src/main/java/tech/ydb/liquibase/type/TimeTypeYdb.java, liquibase-dialect/src/main/java/tech/ydb/liquibase/type/TimestampTypeYdb.java, liquibase-dialect/src/test/java/tech/ydb/liquibase/YdbDatabaseCSVLoadTest.java, liquibase-dialect/src/test/resources/changelogs/csv/test-insert.csv, liquibase-dialect/src/test/resources/changelogs/csv/test-upsert.csv
=> [Liquibase]: Fix NullPointerException

flyway-dialect/pom.xml, flyway-dialect/src/main/java/tech/ydb/flywaydb/database/YdbConnection.java, flyway-dialect/src/main/java/tech/ydb/flywaydb/database/YdbDatabase.java, flyway-dialect/src/main/java/tech/ydb/flywaydb/database/YdbDatabaseType.java, flyway-dialect/src/main/java/tech/ydb/flywaydb/database/YdbParser.java, flyway-dialect/src/main/java/tech/ydb/flywaydb/database/YdbSchema.java, flyway-dialect/src/main/java/tech/ydb/flywaydb/database/YdbTable.java, flyway-dialect/src/main/resources/META-INF/services/org.flywaydb.core.extensibility.Plugin
=> [Flyway]: Initial flyway dialect

flyway-dialect/pom.xml, flyway-dialect/src/main/java/tech/ydb/flywaydb/database/YdbConnection.java, flyway-dialect/src/main/java/tech/ydb/flywaydb/database/YdbDatabase.java, flyway-dialect/src/main/java/tech/ydb/flywaydb/database/YdbDatabaseType.java, flyway-dialect/src/main/java/tech/ydb/flywaydb/database/YdbJdbcTemplate.java, flyway-dialect/src/main/java/tech/ydb/flywaydb/database/YdbSchema.java, flyway-dialect/src/test/java/tech/ydb/flyway/database/YdbFlywayTest.java, flyway-dialect/src/test/resources/db/migration/V1_create_tables.sql
=> [Flyway]: Integration test

liquibase-dialect/src/main/java/tech/ydb/liquibase/database/YdbDatabase.java, liquibase-dialect/src/test/java/tech/ydb/liquibase/BaseTest.java, liquibase-dialect/src/test/java/tech/ydb/liquibase/YdbDatabaseCSVLoadTest.java, liquibase-dialect/src/test/java/tech/ydb/liquibase/YdbDatabaseLiquibaseAllTypesTableTest.java
=> [Liquibase]: supportsDDLInTransaction() return false + fix flap tests

liquibase-dialect/src/main/java/tech/ydb/liquibase/database/YdbDatabase.java, liquibase-dialect/src/main/java/tech/ydb/liquibase/snapshot/UniqueConstraintSnapshotGeneratorYdb.java, liquibase-dialect/src/main/java/tech/ydb/liquibase/type/DecimalTypeYdb.java, liquibase-dialect/src/main/java/tech/ydb/liquibase/type/IntervalTypeYdb.java, liquibase-dialect/src/main/java/tech/ydb/liquibase/type/JsonDocumentTypeYdb.java, liquibase-dialect/src/main/java/tech/ydb/liquibase/type/JsonTypeYdb.java, liquibase-dialect/src/main/resources/META-INF/services/liquibase.datatype.LiquibaseDataType, liquibase-dialect/src/main/resources/META-INF/services/liquibase.snapshot.SnapshotGenerator, liquibase-dialect/src/test/java/tech/ydb/liquibase/YdbDatabaseGenerateChangeLogTest.java, liquibase-dialect/src/test/java/tech/ydb/liquibase/YdbDatabaseLiquibaseAllTypesTableTest.java
=> [Liquibase]: Support generate-changelog

liquibase-dialect/src/main/java/tech/ydb/liquibase/sqlgenerator/CreateTableGeneratorYdb.java, liquibase-dialect/src/test/java/tech/ydb/liquibase/YdbDatabaseGenerateChangeLogTest.java, liquibase-dialect/src/test/java/tech/ydb/liquibase/YdbDatabaseLiquibaseAllTypesTableTest.java, liquibase-dialect/src/test/java/tech/ydb/liquibase/YdbDatabaseLiquibaseChangeLogStateTest.java
=> [Liquibase]: Support NOT NULL column in createTable

.github/workflows/ci-hibernate-dialect-v5.yaml, .github/workflows/ci-hibernate-dialect.yaml, .github/workflows/ci-jooq-dialect.yaml, .github/workflows/ci-liquibase-dialect.yaml, .github/workflows/liquibase-stress-test.yaml
=> feat: [GitHub Actions] fix run after commit and stress test liquibase

README.md, liquibase-dialect/CHANGELOG.md, liquibase-dialect/pom.xml, liquibase-dialect/src/main/java/tech/ydb/liquibase/type/DecimalTypeYdb.java, liquibase-dialect/src/main/java/tech/ydb/liquibase/type/IntTypeYdb.java, liquibase-dialect/src/main/java/tech/ydb/liquibase/type/TimeTypeYdb.java, liquibase-dialect/src/main/java/tech/ydb/liquibase/type/TimestampTypeYdb.java, liquibase-dialect/src/test/java/tech/ydb/liquibase/YdbDatabaseGenerateChangeLogTest.java, liquibase-dialect/src/test/java/tech/ydb/liquibase/YdbDatabaseLiquibaseAllTypesTableTest.java
=> feat: [Liquibase] release 1.0.0

liquibase-dialect/src/main/java/tech/ydb/liquibase/sqlgenerator/SelectFromDatabaseChangeLogGeneratorYdb.java, liquibase-dialect/src/main/resources/META-INF/services/liquibase.sqlgenerator.SqlGenerator, liquibase-dialect/src/test/java/tech/ydb/liquibase/BaseTest.java, liquibase-dialect/src/test/java/tech/ydb/liquibase/YdbDatabaseReadBigChangeLogTest.java, liquibase-dialect/src/test/resources/changelogs/changelog-init.xml
=> [Liquibase]: SCAN SELECT * FROM DATABASECHANGELOG

liquibase-dialect/src/main/java/tech/ydb/liquibase/type/DateTypeYdb.java, liquibase-dialect/src/main/java/tech/ydb/liquibase/type/IntervalTypeYdb.java, liquibase-dialect/src/main/java/tech/ydb/liquibase/type/TimestampTypeYdb.java, liquibase-dialect/src/test/java/tech/ydb/liquibase/YdbDatabaseCSVLoadTest.java, liquibase-dialect/src/test/resources/changelogs/changelog_all_types_table.xml, liquibase-dialect/src/test/resources/changelogs/csv/test-insert.csv, liquibase-dialect/src/test/resources/changelogs/csv/test-upsert.csv
=> [Liquibase]: Interval is duration format and Timestamp is ISO Format

flyway-dialect/pom.xml, flyway-dialect/src/main/java/tech/ydb/flywaydb/database/YdbConnection.java, flyway-dialect/src/main/java/tech/ydb/flywaydb/database/YdbDatabase.java, flyway-dialect/src/main/java/tech/ydb/flywaydb/database/YdbJdbcTemplate.java, flyway-dialect/src/main/java/tech/ydb/flywaydb/database/YdbSchema.java, flyway-dialect/src/main/java/tech/ydb/flywaydb/database/YdbTable.java, liquibase-dialect/pom.xml
=> [Flyway]: Impl LockService

.github/workflows/ci-flyway-dialect.yaml, .github/workflows/publish-flyway-dialect.yaml
=> [Flyway]: GitHub actions CI and Publish

jooq-dialect/pom.xml, jooq-dialect/src/main/java/tech/ydb/jooq/codegen/YdbDatabase.java, jooq-dialect/src/test/java/tech/ydb/jooq/ReplaceTest.java
Please check the type of change your PR introduces:
Issue Number: #128
- Driver has been updated to a version where REPLACE works
- REPLACE tests have been added
=> [JOOQ]: Update JDBC driver to 2.1.2
